/*     electric love #jdragon
⠀⠀⠀⠀⠀⠀⠀⠀⠀⣠⠤⠖⠚⢉⣩⣭⡭⠛⠓⠲⠦⣄⡀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⢀⡴⠋⠁⠀⠀⠊⠀⠀⠀⠀⠀⠀⠀⠀⠀⠉⠳⢦⡀⠀⠀⠀⠀
⠀⠀⠀⠀⢀⡴⠃⢀⡴⢳⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠙⣆⠀⠀⠀
⠀⠀⠀⠀⡾⠁⣠⠋⠀⠈⢧⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⢧⠀⠀
⠀⠀⠀⣸⠁⢰⠃⠀⠀⠀⠈⢣⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⣇⠀
⠀⠀⠀⡇⠀⡾⡀⠀⠀⠀⠀⣀⣹⣆⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢹⠀
⠀⠀⢸⠃⢀⣇⡈⠀⠀⠀⠀⠀⠀⢀⡑⢄⡀⢀⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢸⡇
⠀⠀⢸⠀⢻⡟⡻⢶⡆⠀⠀⠀⠀⡼⠟⡳⢿⣦⡑⢄⠀⠀⠀⠀⠀⠀⠀⠀⢸⡇
⠀⠀⣸⠀⢸⠃⡇⢀⠇⠀⠀⠀⠀⠀⡼⠀⠀⠈⣿⡗⠂⠀⠀⠀⠀⠀⠀⠀⢸⠁
⠀⠀⡏⠀⣼⠀⢳⠊⠀⠀⠀⠀⠀⠀⠱⣀⣀⠔⣸⠁⠀⠀⠀⠀⠀⠀⠀⢠⡟⠀
⠀⠀⡇⢀⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠠⠀⡇⠀⠀⠀⠀⠀⠀⠀⠀⢸⠃⠀
⠀⢸⠃⠘⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢸⠁⠀⠀⢀⠀⠀⠀⠀⠀⣾⠀⠀
⠀⣸⠀⠀⠹⡄⠀⠀⠈⠁⠀⠀⠀⠀⠀⠀⠀⡞⠀⠀⠀⠸⠀⠀⠀⠀⠀⡇⠀⠀
⠀⡏⠀⠀⠀⠙⣆⠀⠀⠀⠀⠀⠀⠀⢀⣠⢶⡇⠀⠀⢰⡀⠀⠀⠀⠀⠀⡇⠀⠀
⢰⠇⡄⠀⠀⠀⡿⢣⣀⣀⣀⡤⠴⡞⠉⠀⢸⠀⠀⠀⣿⡇⠀⠀⠀⠀⠀⣧⠀⠀
⣸⠀⡇⠀⠀⠀⠀⠀⠀⠉⠀⠀⠀⢹⠀⠀⢸⠀⠀⢀⣿⠇⠀⠀⠀⠁⠀⢸⠀⠀
⣿⠀⡇⠀⠀⠀⠀⠀⢀⡤⠤⠶⠶⠾⠤⠄⢸⠀⡀⠸⣿⣀⠀⠀⠀⠀⠀⠈⣇⠀
⡇⠀⡇⠀⠀⡀⠀⡴⠋⠀⠀⠀⠀⠀⠀⠀⠸⡌⣵⡀⢳⡇⠀⠀⠀⠀⠀⠀⢹⡀
⡇⠀⠇⠀⠀⡇⡸⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠙⠮⢧⣀⣻⢂⠀⠀⠀⠀⠀⠀⢧
⣇⠀⢠⠀⠀⢳⠇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⡎⣆⠀⠀⠀⠀⠀⠘
⢻⠀⠈⠰⠀⢸⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠰⠘⢮⣧⡀⠀⠀⠀⠀
⠸⡆⠀⠀⠇⣾⠀⠀⠀⠀⠀⠀⠀⠀⠀⢠⠆⠀⠀⠀⠀⠀⠀⠀⠙⠳⣄⡀⢢⡀
 oregairu */ 
#include "bits/stdc++.h"
using namespace std;
#define ll long long
#define fl i,a,b for(int i=a;i<b;i++)
#define co cout<<
#define ci cin>>
#define rep(i,x,n) for(long long i = x; i < n; i++) 
#define rev(i,n,x) for(long long i = n; i >= x; --i)
#define ff            first
#define ss            second
#define vecll vector<long long>
#define pii pair<long long ,long long >
#define pip pair<int,pair<int,int>>
#define ppp pair<pair<int,int>,pair<int,int>>
#define inarr(arr,x,n)  for(ll i=x ;i<n;i++) cin >> arr[i];
#define carr(v,x,n)  for(ll i=x ;i<n;i++) cout << v[i]-v[i-1]<<" ";
#define mpp make_pair
#define pb               push_back
#define ppb               pop_back
#define all(x)          (x).begin(),(x).end()
#define sz(x)           (x).size()
#define henshin           cout<<endl;
#define DEBUG(x) cout << (x) << '\n';
#define int long long 
const ll oo = 1e18;
inline void yn(int x) { if(!x)cout << "NO\n";  else if(x)cout << "YES\n";return; }

const ll N=1e5+5,M=1e9+7,mod=1e9+7;
  const int MAXA = 1e5+1; 
 
// vector<int> primes;
//    int mind[MAXA+1];
 
 
 
void solve(){
int n,m,k;
  ci n>>m>>k; 
int xj[600][600]={{0}};
int xi[600][600]={{0}};
int dp[600][600][21]={{{0}}};

for(int i=1;i<=n;i++)
    for(int j=1;j<=m-1;j++)
       ci xj[i][j]; 

for(int i=1;i<=n-1;i++)
    for(int j=1;j<=m;j++)
      ci xi[i][j]; 

if(k%2==1)
     for(int i=1;i<=n;i++){
              for(int j=1;j<=m;j++)
                 co "-1 ";
                 henshin}
        
if(k%2==1)return;

for(int x=1;x<=k/2;x++)
    for(int i=1;i<=n;i++)
        for(int j=1;j<=m;j++){dp[i][j][x]=oo;
                   if(j<m)dp[i][j][x]= dp[i][j+1][x-1]+xj[i][j] ;
                   if(j>1)dp[i][j][x]=min(dp[i][j][x],dp[i][j-1][x-1]+xj[i][j-1]);
                   if(i<n)dp[i][j][x]=min(dp[i][j][x],dp[i+1][j][x-1]+xi[i][j]);
                   if(i>1)dp[i][j][x]=min(dp[i][j][x],dp[i-1][j][x-1]+xi[i-1][j]);

        }

for(int i=1;i<=n;i++) {
    for(int j=1;j<=m;j++)
        co dp[i][j][k/2] * 2<<" ";
             
henshin }

} 





 
signed main() {
 
    ios_base::sync_with_stdio(false);
    cin.tie(0), cout.tie(0);
    cout << fixed << setprecision(15);

 /* 
  for (int i = 2; i <= MAXA; ++i) {
        if (mind[i] == 0) {
            primes.emplace_back(i);
            mind[i] = i;
        }
        for (auto &x : primes) {
            if (x > mind[i] || x * i > MAXA) break;
            mind[x * i] = x;
        }
    }
 */   
 
    int tc=1;   
   //ci tc;
    while(tc--) { 
    solve();
    }
    return 0;
}
