/*     electric love #jdragon
⠀⠀⠀⠀⠀⠀⠀⠀⠀⣠⠤⠖⠚⢉⣩⣭⡭⠛⠓⠲⠦⣄⡀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⢀⡴⠋⠁⠀⠀⠊⠀⠀⠀⠀⠀⠀⠀⠀⠀⠉⠳⢦⡀⠀⠀⠀⠀
⠀⠀⠀⠀⢀⡴⠃⢀⡴⢳⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠙⣆⠀⠀⠀
⠀⠀⠀⠀⡾⠁⣠⠋⠀⠈⢧⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⢧⠀⠀
⠀⠀⠀⣸⠁⢰⠃⠀⠀⠀⠈⢣⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⣇⠀
⠀⠀⠀⡇⠀⡾⡀⠀⠀⠀⠀⣀⣹⣆⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢹⠀
⠀⠀⢸⠃⢀⣇⡈⠀⠀⠀⠀⠀⠀⢀⡑⢄⡀⢀⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢸⡇
⠀⠀⢸⠀⢻⡟⡻⢶⡆⠀⠀⠀⠀⡼⠟⡳⢿⣦⡑⢄⠀⠀⠀⠀⠀⠀⠀⠀⢸⡇
⠀⠀⣸⠀⢸⠃⡇⢀⠇⠀⠀⠀⠀⠀⡼⠀⠀⠈⣿⡗⠂⠀⠀⠀⠀⠀⠀⠀⢸⠁
⠀⠀⡏⠀⣼⠀⢳⠊⠀⠀⠀⠀⠀⠀⠱⣀⣀⠔⣸⠁⠀⠀⠀⠀⠀⠀⠀⢠⡟⠀
⠀⠀⡇⢀⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠠⠀⡇⠀⠀⠀⠀⠀⠀⠀⠀⢸⠃⠀
⠀⢸⠃⠘⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢸⠁⠀⠀⢀⠀⠀⠀⠀⠀⣾⠀⠀
⠀⣸⠀⠀⠹⡄⠀⠀⠈⠁⠀⠀⠀⠀⠀⠀⠀⡞⠀⠀⠀⠸⠀⠀⠀⠀⠀⡇⠀⠀
⠀⡏⠀⠀⠀⠙⣆⠀⠀⠀⠀⠀⠀⠀⢀⣠⢶⡇⠀⠀⢰⡀⠀⠀⠀⠀⠀⡇⠀⠀
⢰⠇⡄⠀⠀⠀⡿⢣⣀⣀⣀⡤⠴⡞⠉⠀⢸⠀⠀⠀⣿⡇⠀⠀⠀⠀⠀⣧⠀⠀
⣸⠀⡇⠀⠀⠀⠀⠀⠀⠉⠀⠀⠀⢹⠀⠀⢸⠀⠀⢀⣿⠇⠀⠀⠀⠁⠀⢸⠀⠀
⣿⠀⡇⠀⠀⠀⠀⠀⢀⡤⠤⠶⠶⠾⠤⠄⢸⠀⡀⠸⣿⣀⠀⠀⠀⠀⠀⠈⣇⠀
⡇⠀⡇⠀⠀⡀⠀⡴⠋⠀⠀⠀⠀⠀⠀⠀⠸⡌⣵⡀⢳⡇⠀⠀⠀⠀⠀⠀⢹⡀
⡇⠀⠇⠀⠀⡇⡸⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠙⠮⢧⣀⣻⢂⠀⠀⠀⠀⠀⠀⢧
⣇⠀⢠⠀⠀⢳⠇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⡎⣆⠀⠀⠀⠀⠀⠘
⢻⠀⠈⠰⠀⢸⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠰⠘⢮⣧⡀⠀⠀⠀⠀
⠸⡆⠀⠀⠇⣾⠀⠀⠀⠀⠀⠀⠀⠀⠀⢠⠆⠀⠀⠀⠀⠀⠀⠀⠙⠳⣄⡀⢢⡀
 oregairu */ 
#include "bits/stdc++.h"
using namespace std;
#define ll long long
#define fl i,a,b for(int i=a;i<b;i++)
#define co cout<<
#define ci cin>>
#define rep(i,x,n) for(long long i = x; i < n; i++) 
#define rev(i,n,x) for(long long i = n; i >= x; --i)
#define ff            first
#define ss            second
#define vecll vector<long long>
#define pii pair<long long ,long long >
#define pip pair<int,pair<int,int>>
#define ppp pair<pair<int,int>,pair<int,int>>
#define inarr(arr,x,n)  for(ll i=x ;i<n;i++) cin >> arr[i];
#define carr(v,x,n)  for(ll i=x ;i<n;i++) cout << v[i]-v[i-1]<<" ";
#define mpp make_pair
#define pb               push_back
#define ppb               pop_back
#define all(x)          (x).begin(),(x).end()
#define sz(x)           (x).size()
#define henshin           cout<<endl;
#define DEBUG(x) cout << (x) << '\n';
#define int long long 
const ll oo = 1e18;
inline void yn(int x) { if(!x)cout << "NO\n";  else if(x)cout << "YES\n";return; }

const ll N=1e7+1,M=1e5+7,mod=1e9+7;
  const int MAXA = 1e7+5; 
 int mind[MAXA+5]={0};

  
 



void solve(){
 ll n,k; ci n>>k;ll c=1;
 if (n < 64 && k > (1LL << (n - 1))) { DEBUG(-1) return; }

 int a[n]={0};k--;

for(ll b = 0; b < min(60LL, (ll)(n - 1)); b++) {
        if((k >> b) & 1)
            a[n - 2 - b] = 1;
    }
 
int cur = 1, sz = 1;
 vector<int> ans;
    for(int i = 0; i < n; i++) {
        if(a[i] == 0) {
            for(int j = cur + sz - 1; j >= cur; j--)
                ans.push_back(j);
            cur += sz;
            sz = 1;
        }
        else
            sz++;
    }

for(auto &x : ans) co x<<" ";

henshin} 





 
signed main() {
 
    ios_base::sync_with_stdio(false);
    cin.tie(0), cout.tie(0);
    cout << fixed << setprecision(15);

/*  
for (int i = 2; i * i < N; i++) {
    if (mind[i] == 0) {
      mind[i] = i;
      for (int j = i * i; j < N; j += i) {
        if (mind[j] == 0) {
          mind[j] = i;
        }
      }
    }
  }
*/
    
    int tc=1;   
   ci tc;
    while(tc--) { 
    solve();
    }
    return 0;
}
